import type { BookReference, ShelfStatus } from "./types";

type Row = readonly [title: string, authors: string, domain: string, status?: ShelfStatus];

/* Bibliographic registry only. No title in this file implies possession of, or
 * permission to ingest, its full text. Entries 86–95 still require an exact
 * edition and jurisdiction gate before any download. */
const ROWS: Row[] = [
  ["Psychology – H5P Edition", "Spielman et al. / BCcampus", "psychology", "FULL_INGEST_CANDIDATE"],
  ["Thinking, Fast and Slow", "Daniel Kahneman", "cognition"], ["Noise", "Kahneman, Sibony, Sunstein", "judgment"],
  ["Nudge", "Thaler, Sunstein", "choice architecture"], ["Misbehaving", "Richard Thaler", "behavioral economics"],
  ["Predictably Irrational", "Dan Ariely", "judgment"], ["The Scout Mindset", "Julia Galef", "epistemics"],
  ["Superforecasting", "Tetlock, Gardner", "forecasting"], ["Rationality", "Steven Pinker", "reasoning"],
  ["The Intelligence Trap", "David Robson", "reasoning"], ["Thinking in Bets", "Annie Duke", "decision making"],
  ["How Minds Change", "David McRaney", "persuasion"], ["Mistakes Were Made (But Not by Me)", "Tavris, Aronson", "self-justification"],
  ["The Person and the Situation", "Ross, Nisbett", "social psychology"], ["The Righteous Mind", "Jonathan Haidt", "moral psychology"],
  ["Behave", "Robert Sapolsky", "behavior"], ["The Invisible Gorilla", "Chabris, Simons", "attention"],
  ["The Seven Sins of Memory", "Daniel Schacter", "memory"], ["The Memory Illusion", "Julia Shaw", "memory"],
  ["Why We Remember", "Charan Ranganath", "memory"],
  ["Getting to Yes", "Fisher, Ury, Patton", "negotiation"], ["Difficult Conversations", "Stone, Patton, Heen", "conflict"],
  ["Beyond Reason", "Fisher, Shapiro", "negotiation"], ["Negotiation Genius", "Malhotra, Bazerman", "negotiation"],
  ["3-D Negotiation", "Lax, Sebenius", "negotiation"], ["Bargaining for Advantage", "G. Richard Shell", "negotiation"],
  ["The Mind and Heart of the Negotiator", "Leigh Thompson", "negotiation"], ["Getting More", "Stuart Diamond", "negotiation"],
  ["Never Split the Difference", "Voss, Raz", "negotiation"], ["Influence", "Robert Cialdini", "persuasion"],
  ["Pre-Suasion", "Robert Cialdini", "persuasion"], ["Yes! 50 Scientifically Proven Ways to Be Persuasive", "Goldstein, Martin, Cialdini", "persuasion"],
  ["Influence Is Your Superpower", "Zoe Chance", "influence"], ["The Power of a Positive No", "William Ury", "boundaries"],
  ["Thanks for the Feedback", "Stone, Heen", "feedback"], ["Crucial Conversations", "Patterson et al.", "conflict"],
  ["The Anatomy of Peace", "The Arbinger Institute", "conflict"], ["Getting Past No", "William Ury", "negotiation"],
  ["The Art of Negotiation", "Michael Wheeler", "negotiation"], ["The Power of Noticing", "Max Bazerman", "attention"],
  ["The Social Animal", "Elliot Aronson", "social psychology"], ["The Presentation of Self in Everyday Life", "Erving Goffman", "social dynamics"],
  ["The Elephant in the Brain", "Simler, Hanson", "motives"], ["The Status Game", "Will Storr", "status"],
  ["The Lucifer Effect", "Philip Zimbardo", "social psychology"], ["Social: Why Our Brains Are Wired to Connect", "Matthew Lieberman", "social psychology"],
  ["The Power Paradox", "Dacher Keltner", "power"], ["Trust and Distrust in Organizations", "Kramer, Cook (eds.)", "trust"],
  ["The Culture Map", "Erin Meyer", "culture"], ["The Wisest One in the Room", "Gilovich, Ross", "social psychology"],
  ["The Enigma of Reason", "Mercier, Sperber", "reasoning"], ["The Knowledge Illusion", "Sloman, Fernbach", "reasoning"],
  ["The Honest Truth About Dishonesty", "Dan Ariely", "dishonesty"], ["The Confidence Game", "Maria Konnikova", "deception"],
  ["The Undoing Project", "Michael Lewis", "history of judgment"],
  ["Detecting Lies and Deceit", "Aldert Vrij", "deception"], ["Telling Lies", "Paul Ekman", "deception"],
  ["Spy the Lie", "Houston, Floyd, Carnicero, Tennant", "deception"], ["The Like Switch", "Schafer, Karlins", "rapport"],
  ["What Every BODY Is Saying", "Joe Navarro", "body-language claims"], ["Talking to Strangers", "Malcolm Gladwell", "communication"],
  ["The Full Facts Book of Cold Reading", "Ian Rowland", "mentalism"], ["13 Steps to Mentalism", "Tony Corinda", "mentalism"],
  ["Practical Mental Magic", "Theodore Annemann", "mentalism"], ["Psychological Subtleties", "Banachek", "mentalism"],
  ["Pure Effect", "Derren Brown", "mentalism"], ["Tricks of the Mind", "Derren Brown", "mentalism"],
  ["Maximum Entertainment", "Ken Weber", "performance"], ["The Definitive Book of Body Language", "Allan and Barbara Pease", "body-language claims"],
  ["The Science of Interrogation and Confessions", "academic reference family", "ethical interviewing"],
  ["Lateral Thinking", "Edward de Bono", "creativity"], ["Six Thinking Hats", "Edward de Bono", "creativity"],
  ["Serious Creativity", "Edward de Bono", "creativity"], ["Thinkertoys", "Michael Michalko", "creativity"],
  ["A Technique for Producing Ideas", "James Webb Young", "creativity"], ["The Art of Thought", "Graham Wallas", "creativity"],
  ["Creative Confidence", "Tom Kelley, David Kelley", "creativity"], ["The Creative Act", "Rick Rubin", "creativity"],
  ["Range", "David Epstein", "learning"], ["Originals", "Adam Grant", "creativity"], ["Think Again", "Adam Grant", "reasoning"],
  ["Decisive", "Chip Heath, Dan Heath", "decision making"], ["The Art of Strategy", "Dixit, Nalebuff", "strategy"],
  ["Good Strategy/Bad Strategy", "Richard Rumelt", "strategy"], ["The Strategy of Conflict", "Thomas Schelling", "strategy"],
  ["The Adventures of Sherlock Holmes", "Arthur Conan Doyle", "detective fiction", "PUBLIC_DOMAIN_CANDIDATE"],
  ["The Memoirs of Sherlock Holmes", "Arthur Conan Doyle", "detective fiction", "PUBLIC_DOMAIN_CANDIDATE"],
  ["The Hound of the Baskervilles", "Arthur Conan Doyle", "detective fiction", "PUBLIC_DOMAIN_CANDIDATE"],
  ["A Study in Scarlet", "Arthur Conan Doyle", "detective fiction", "PUBLIC_DOMAIN_CANDIDATE"],
  ["The Sign of the Four", "Arthur Conan Doyle", "detective fiction", "PUBLIC_DOMAIN_CANDIDATE"],
  ["The Innocence of Father Brown", "G. K. Chesterton", "detective fiction", "PUBLIC_DOMAIN_CANDIDATE"],
  ["The Wisdom of Father Brown", "G. K. Chesterton", "detective fiction", "PUBLIC_DOMAIN_CANDIDATE"],
  ["The Red Thumb Mark", "R. Austin Freeman", "detective fiction", "PUBLIC_DOMAIN_CANDIDATE"],
  ["The Thinking Machine / The Problem of Cell 13", "Jacques Futrelle", "detective fiction", "PUBLIC_DOMAIN_CANDIDATE"],
  ["C. Auguste Dupin trilogy", "Edgar Allan Poe", "detective fiction", "PUBLIC_DOMAIN_CANDIDATE"],
  ["PubMed Central Open Access Subset", "U.S. National Library of Medicine", "research infrastructure", "FULL_INGEST_CANDIDATE"],
  ["APA Dictionary of Psychology", "American Psychological Association", "reference"],
  ["Harvard Program on Negotiation", "Harvard University", "negotiation reference"],
  ["Noba Project psychology modules", "Noba Project", "psychology reference"],
  ["FBI crisis/hostage negotiation educational materials", "Federal Bureau of Investigation", "crisis negotiation reference"],
];

export const BOOK_SHELF: BookReference[] = ROWS.map(([title, authors, domain, status], index) => ({
  id: `book-${String(index + 1).padStart(3, "0")}`,
  type: "BOOK_REFERENCE",
  title,
  authors,
  year: null,
  domain,
  reason_for_inclusion: `Curated reference for ${domain}; not an empirical claim by itself.`,
  high_level_topics: [domain],
  legal_access_status: status ?? "REFERENCE_ONLY",
  source_registry: "ULIKA curated 100-source shelf, 2026-08-22",
}));

if (BOOK_SHELF.length !== 100) throw new Error(`BOOK_SHELF_COUNT_${BOOK_SHELF.length}`);
