import type { KnowledgeEntry } from "./craft";

/**
 * The psychology bookshelf, written as original working notes.
 *
 * Deliberately NOT excerpts. Copying book text would be both a copyright
 * problem and worse material — what a practitioner needs is the mechanism,
 * what it lets you see, how it is used live, and where it fails. Popular
 * summaries almost always drop that last part, so it is mandatory here.
 */
export const PSYCHOLOGY: KnowledgeEntry[] = [
  {
    id: "kahneman-systems",
    title: "Two systems, and the biases that fall out of them (Kahneman)",
    cues: ["decision", "decide", "gut", "instinct", "rushed", "impulse", "bias", "judgement", "overthinking", "regret"],
    core:
      "Thinking runs in two modes. System 1 is fast, automatic, emotional and always on. System 2 is slow, effortful, and lazy — it mostly endorses whatever System 1 already produced. Most errors are not System 1 malfunctioning; they are System 2 failing to check it. Anchoring, availability (judging likelihood by how easily an example comes to mind), loss aversion (losses hurt roughly twice as much as equivalent gains please), and the halo effect all come out of this structure.",
    reveals:
      "Why someone is certain and wrong at the same time, with no felt difference from being certain and right. Confidence is generated by the coherence of the story, not by the quality of the evidence.",
    inPractice:
      "When someone reports a strong immediate reaction, treat it as data about them rather than about the situation. Ask what the first thing they thought was, then what the second thing was. The gap between those two is usually where the useful material lives.",
    limits:
      "Several famous studies in this area have replicated poorly, especially priming work. The two-system framing is a useful model, not a map of brain anatomy, and Kahneman himself publicly walked back parts of it.",
  },
  {
    id: "gottman-horsemen",
    title: "The four patterns that predict a relationship ending (Gottman)",
    cues: ["relationship", "partner", "wife", "husband", "girlfriend", "boyfriend", "marriage", "fight", "argue", "breaking up", "divorce"],
    core:
      "From observing thousands of couples, four interaction patterns predict dissolution far better than the content of any disagreement. Criticism (attacking character rather than behaviour: you're selfish, versus I was upset you didn't call). Contempt — eye-rolling, mockery, superiority — which is the single strongest predictor. Defensiveness, including counter-attack and playing victim. Stonewalling, shutting down and withdrawing entirely. What predicts survival is not the absence of conflict but the presence of repair attempts, and whether they get accepted.",
    reveals:
      "That how people fight matters more than what they fight about. Also that contempt specifically is a different category from anger — anger can coexist with a good relationship, contempt basically cannot.",
    inPractice:
      "When someone describes a recurring conflict, listen for which of the four is running, on both sides. Then ask about repair: what happens after? Who moves first? Does the other person accept it? That question is far more diagnostic than the details of the last argument.",
    limits:
      "The famous prediction accuracy figures come from models fitted and tested in ways that inflate them, and the effect is weaker in genuine out-of-sample prediction. The four patterns remain clinically useful as descriptions even where the prediction claims are overstated.",
  },
  {
    id: "attachment",
    title: "Attachment patterns in adult conflict",
    cues: ["clingy", "distant", "needy", "space", "abandoned", "smothered", "anxious", "avoid", "pull away", "ex", "trust issues"],
    core:
      "People carry a default strategy for what to do when a close relationship feels threatened. Roughly: anxious strategies escalate to re-establish contact — more calls, more texts, more pressing for reassurance. Avoidant strategies deactivate — go quiet, get busy, need space, minimise the importance of the relationship. Secure strategies can state the need directly and tolerate the wait. The classic destructive loop is anxious pursuing an avoidant, where each strategy directly triggers the other.",
    reveals:
      "Why two people can both be acting in good faith and produce a pattern that feels deliberately cruel to both. The pursuit reads as attack; the withdrawal reads as abandonment.",
    inPractice:
      "When someone describes a partner who goes cold, or one who will not stop pushing, the useful move is to name the loop rather than assign a villain. Ask what happens in the first ten minutes after things get tense — that is where the strategy shows itself most clearly.",
    limits:
      "These are tendencies, not types, and they shift by relationship and over time. Treating attachment style as a fixed personality label — and especially as a diagnosis you hand to someone else — is a misuse. It also does not excuse behaviour. A pattern explains, it does not license.",
  },
  {
    id: "nvc",
    title: "Observation, feeling, need, request (Rosenberg)",
    cues: ["tell them", "confront", "conversation", "bring it up", "how do i say", "express", "communicate", "ask for"],
    core:
      "A four-part structure for saying a hard thing without triggering defence. State the observation as a camera would record it, with no evaluation. Name the feeling it produced in you. Name the need underneath the feeling. Make one concrete, present-tense, doable request. The power is in the separation: most conflict escalates because an evaluation is smuggled in as an observation, and the other person correctly hears an accusation.",
    reveals:
      "How much of what people call describing what happened is actually a verdict. You were dismissive is a verdict. You checked your phone twice while I was talking is an observation. The second one is very hard to argue with.",
    inPractice:
      "When someone is rehearsing a confrontation, have them strip the evaluation out of their opening line first. That single edit changes the outcome of the conversation more than anything else they can prepare.",
    limits:
      "Delivered rigidly it sounds robotic and can read as condescending, which produces exactly the defence it was meant to avoid. It also assumes a counterpart engaging in good faith. Against someone actively hostile or manipulative, this framework is not the tool.",
  },
  {
    id: "cbt-distortions",
    title: "Cognitive distortions (Beck, Burns)",
    cues: ["always", "never", "everyone", "nobody", "ruined", "disaster", "failure", "worthless", "catastrophe", "spiral"],
    core:
      "Recurring shapes of inaccurate thinking that keep low mood running. All-or-nothing framing. Overgeneralising from one instance (this always happens). Mind reading — assuming you know what someone thinks without evidence. Fortune telling. Catastrophising. Emotional reasoning, where the intensity of a feeling is taken as proof of the fact. Personalising, taking responsibility for things outside your causal reach. Should statements, which generate guilt without generating action.",
    reveals:
      "That the distress is often being manufactured by the shape of the thought rather than by the event. Two people can experience the same event and only one of them catastrophises it.",
    inPractice:
      "Listen for absolute quantifiers — always, never, everyone, nobody. They are the loudest audible marker. Rather than correcting them, ask for the counter-example directly: has there been a single time it went differently? The person finding it themselves does the work.",
    limits:
      "Not every dark thought is a distortion. Sometimes the job really is bad and the relationship really is failing, and reframing an accurate perception is gaslighting with a friendly face. Check the evidence before labelling the thought.",
  },
  {
    id: "motivational-interviewing",
    title: "Rolling with resistance (Miller, Rollnick)",
    cues: ["won't listen", "stubborn", "keeps doing", "can't get them to", "change", "habit", "quit", "convince them"],
    core:
      "Arguing for change makes a person argue against it. Because people believe their own speech, pushing someone toward a decision reliably produces them voicing the case for staying the same, which entrenches it. The alternative is to elicit the change talk from them: ask what they like about the current situation and what worries them about it, and let the ambivalence be spoken out loud by the person who owns it.",
    reveals:
      "Why the more you push someone toward an obvious good decision, the more committed they become to the bad one. The resistance is generated by the pushing, not by the topic.",
    inPractice:
      "When someone wants to know how to make another person change, redirect entirely. The question that works is what does this person get out of the current behaviour. Nobody maintains a costly habit for no return, and the return is the actual problem to solve.",
    limits:
      "This is a clinical method requiring real training, and the summary version can become a manipulative technique for steering people while appearing neutral. It is also not appropriate where someone is in immediate danger.",
  },
  {
    id: "transactional-analysis",
    title: "Which version of you showed up (Berne)",
    cues: ["treated me like a child", "condescending", "lecture", "boss", "authority", "defensive", "sulking", "power"],
    core:
      "In any exchange each party occupies one of three stances. Parent: instructing, judging, protecting, using should. Adult: dealing with the situation as it is, gathering information, negotiating. Child: reacting emotionally, complying, rebelling, sulking. Trouble comes from crossed transactions — one person addresses the other as Adult but is answered from Child, or one slips into Parent and drags the other into Child.",
    reveals:
      "Why a conversation about a spreadsheet turned into a conversation about respect. Also why some people reliably make you feel like a teenager, which is a fact about the transaction, not about you.",
    inPractice:
      "When someone reports being talked down to, ask what stance they answered from. The most useful intervention is usually not to demand the other person stop being Parent, but to keep answering as Adult, which quietly removes the counterpart the Parent stance needs.",
    limits:
      "The vocabulary is dated and the wider theory has little empirical support. Use it as a lens for noticing the shape of an exchange, not as a model of personality.",
  },
  {
    id: "self-determination",
    title: "Autonomy, competence, relatedness (Deci, Ryan)",
    cues: ["motivation", "unmotivated", "burnout", "hate my job", "pointless", "lost interest", "procrastinating", "drained"],
    core:
      "Durable motivation depends on three conditions: autonomy (I have some say in how this is done), competence (I can see myself getting better), and relatedness (this connects me to people I care about). Where these hold, motivation is self-sustaining. Where one is missing, external rewards can compensate briefly and then usually make it worse, because being paid to do something can replace the internal reason with an external one.",
    reveals:
      "Which of the three is actually missing. Burnout attributed to workload very often turns out to be an autonomy problem — the same hours are tolerable when the person controls how the work gets done.",
    inPractice:
      "When someone has lost motivation for something they used to want, run the three. Do you have any say in how? Can you see yourself improving? Does anyone you care about care about this? The one that produces a flat no is the actual problem, and it is rarely the one they came in blaming.",
    limits:
      "Not every motivation problem is psychological. Sometimes the pay is too low, the manager is hostile, or the person is exhausted. Reframing a structural problem as a needs problem puts the burden on the wrong party.",
  },
  {
    id: "growth-mindset",
    title: "Fixed and growth framing (Dweck)",
    cues: ["not good at", "no talent", "can't learn", "too old", "not smart enough", "natural", "gifted", "failure"],
    core:
      "Whether someone treats ability as fixed or developable changes what a setback means to them. Under a fixed frame, failure is evidence about identity, so the rational move is to avoid challenges that could produce it. Under a growth frame, failure is information about method, so difficulty becomes worth seeking.",
    reveals:
      "Why a capable person avoids the exact task that would make them better. It is usually not laziness, it is that attempting it puts their self-concept at stake.",
    inPractice:
      "Listen for identity language versus method language. I'm bad at this is identity. I haven't found an approach that works is method. Moving the sentence from the first to the second is often the whole intervention.",
    limits:
      "The effect sizes in real educational interventions are much smaller than the popular version promises, and large replication attempts have been underwhelming. Also, praising effort while someone repeats an ineffective method is useless. Effort with feedback is the thing, not effort.",
  },
  {
    id: "boundaries",
    title: "Boundaries as your own behaviour, not their rules",
    cues: ["boundary", "boundaries", "say no", "guilt", "used", "taken advantage", "family", "toxic", "drains me", "obligation"],
    core:
      "A boundary is a statement about what you will do, not an instruction about what someone else must do. If you keep raising your voice, I'm going to end the call is a boundary. Stop raising your voice is a request, and it depends entirely on their compliance. The distinction matters because only one of these is enforceable by you alone.",
    reveals:
      "Why so many attempts at setting boundaries fail. They were requests, the other person declined, and the person is left feeling both unheard and powerless.",
    inPractice:
      "When someone says they set a boundary and it did not work, ask exactly what they said. Almost always it was a demand. Then ask what they will do the next time it happens, which is the boundary they have not yet made.",
    limits:
      "Boundaries require the ability to follow through, which is not equally available to everyone. Someone financially dependent, sharing custody, or facing an unsafe person cannot simply enforce. Prescribing boundaries without accounting for real constraints is careless advice.",
  },
  {
    id: "fundamental-attribution",
    title: "Their character, your circumstances",
    cues: ["they're just", "he's a", "she's a", "selfish", "rude", "lazy", "typical", "always like that", "person like that"],
    core:
      "Explaining other people's behaviour by their character while explaining your own identical behaviour by your circumstances. They were late because they are inconsiderate; you were late because traffic was bad. It runs constantly and mostly invisibly, and it is the engine underneath most durable interpersonal grudges.",
    reveals:
      "That a story about someone being a certain kind of person is usually a story with the situation deleted. When a description of another human is entirely traits and contains no context, that absence is doing the work.",
    inPractice:
      "Ask what would have to be going on in their life for this to be a reasonable thing to do. Not as an excuse for them, as an accuracy check. Most of the time the person can generate a plausible answer immediately, which tells them something.",
    limits:
      "Some people really do have stable, hostile patterns, and this correction can be weaponised to talk someone out of a correct read on a person who is genuinely mistreating them. Repeated behaviour across varied situations is character evidence. One instance is not.",
  },
  {
    id: "stoic-control",
    title: "The dichotomy of control (Epictetus)",
    cues: ["can't control", "unfair", "worried", "anxious", "obsessing", "won't change", "out of my hands", "stuck"],
    core:
      "Some things are within your power and some are not, and nearly all avoidable suffering comes from spending effort on the second category. Your judgements, choices and actions are yours. Other people's opinions, other people's decisions, the past, and most outcomes are not. The discipline is not indifference; it is a strict accounting of where effort can actually land.",
    reveals:
      "Where someone's energy is being burned with no possible return. Rumination is almost always effort aimed at the not-yours column.",
    inPractice:
      "Have the person split it literally, in writing, into two columns. The exercise is more effective than the explanation, because people argue with the idea and comply with the sorting.",
    limits:
      "It is easily misread as a reason to accept injustice or stay passive where you do have leverage. Applied to someone in a genuinely bad situation, told to just control their reaction, it becomes a way of blaming them for their own circumstances.",
  },
];
