import type { KnowledgeEntry } from "./craft";

/**
 * Stoicism and ancient philosophy.
 *
 * Written from scratch as working notes. The underlying texts are public
 * domain (Marcus Aurelius, Epictetus, Seneca) but nothing here is a close
 * paraphrase of a translation — these are restructured for use, and each one
 * carries the failure mode, which the popular versions of Stoicism almost
 * always drop.
 *
 * Evidence grade for this whole shelf is mostly C: it is a philosophical
 * tradition, not a research programme. Where a move has been independently
 * tested inside modern therapy it is marked higher, and where the popular
 * version distorts the original it says so.
 */
export const STOICISM: KnowledgeEntry[] = [
  {
    id: "premeditatio",
    title: "Rehearsing the loss before it happens",
    cues: ["anxious", "worry", "what if", "dread", "fear", "lose", "losing", "uncertainty", "catastrophe"],
    core:
      "Deliberately picture the thing going wrong, in specific detail, while calm. Not as superstition and not to brace for impact — to find out what you would actually do. Most dread is unexamined; it survives on being kept vague. The moment you make it concrete you usually discover either that you could handle it, or that there is a preparation you have been avoiding making.",
    reveals:
      "Which fears are about the event and which are about your own imagined helplessness in it. Those feel identical from the inside and need completely different responses.",
    inPractice:
      "Ask what specifically happens the day after the thing you fear. Then the week after. People who cannot answer are usually not afraid of the outcome, they are afraid of a blank.",
    limits:
      "This tips into rumination fast, and the difference is whether it terminates in an action or loops. If someone rehearses the same disaster nightly and never arrives at a plan, this is making things worse, not better. It is also actively harmful for someone with an anxiety disorder, where deliberate catastrophic imagery feeds the thing.",
  },
  {
    id: "view-from-above",
    title: "The view from above",
    cues: ["embarrassed", "humiliated", "everyone saw", "cringe", "obsessing", "small thing", "overthinking"],
    core:
      "Deliberately zoom out until the situation is one event among millions happening at the same moment, to people who will not remember it. This is a perspective device, not a truth claim. The point is that the felt size of a humiliation is generated by proximity, and proximity is something you can adjust on purpose.",
    reveals:
      "How much of the distress was scale rather than substance. Something that survives the zoom-out is worth acting on; something that dissolves was never about the event.",
    inPractice:
      "Ask who will remember this in a year, and whether they will remember it the way the person is currently imagining. Most social humiliations are recalled by everyone except the person they happened to.",
    limits:
      "Applied to someone's grief or to a real injustice, this becomes dismissal wearing philosophy. It is a tool for disproportionate distress, not for proportionate distress. If someone's problem is genuinely large, shrinking it is a lie.",
  },
  {
    id: "amor-fati",
    title: "Working with what actually happened",
    cues: ["shouldn't have", "unfair", "why me", "regret", "if only", "wasted", "back then"],
    core:
      "The Stoic move is not to enjoy misfortune, despite what the slogan version suggests. It is to stop spending energy on the counterfactual. What happened is now the material you have; arguing with it is the one activity guaranteed to produce nothing. The energy freed by dropping the argument is the entire benefit.",
    reveals:
      "How much of someone's effort is going into relitigating a settled fact. Usually far more than they think, and it is invisible to them because it feels like processing.",
    inPractice:
      "Notice how often the words should have appear. Then ask what they are going to do with the situation as it is. The shift from should have to now what is the whole technique.",
    limits:
      "The internet version of this — love your fate, everything happens for a reason — is a real distortion and it is cruel when handed to someone whose situation had no reason and no upside. Accepting a fact is not the same as endorsing it. Someone who was wronged is entitled to call it wrong.",
  },
  {
    id: "role-ethics",
    title: "Playing the part well rather than choosing the part",
    cues: ["stuck in", "have to", "obligation", "role", "responsibility", "resent", "duty", "caring for"],
    core:
      "Epictetus framed life as being handed a role you did not cast yourself in. Your judgement applies to how you play it, not to which one you got. This sounds fatalistic and works better than it sounds, because it separates two questions people habitually merge: whether the situation is fair, and how to conduct yourself inside it.",
    reveals:
      "When someone is unable to act because they are still contesting the assignment. A carer resenting having become one often cannot make a single practical decision until that is separated out.",
    inPractice:
      "Separate the two out loud. You did not choose this and it is not fair. Given that it is yours, what does doing it well look like this week? Both halves matter; skipping the first is why this move usually lands badly.",
    limits:
      "Genuinely usable for circumstances nobody chose — illness, family duty, a bad hand. Genuinely dangerous applied to a situation someone can and should leave. Used carelessly it tells people to be excellent inside a cage they could walk out of.",
  },
  {
    id: "voluntary-discomfort",
    title: "Practising discomfort while it is cheap",
    cues: ["comfort", "soft", "resilience", "cold", "hunger", "discipline", "toughen", "habit"],
    core:
      "Occasionally choosing minor hardship — cold, hunger, an uncomfortable bed, doing without — while nothing is wrong. The purpose is calibration, not toughness theatre. You find out experientially that the discomfort you spend energy avoiding is survivable, which reduces how much of your behaviour is organised around avoiding it.",
    reveals:
      "How much of a routine is preference dressed as necessity. People discover they can do without things they would have said they needed, which changes what feels risky.",
    inPractice:
      "One small, chosen, time-boxed thing. The choosing is load-bearing — imposed hardship builds resentment, not calibration.",
    limits:
      "Modern cold-exposure and fasting cultures have attached large physiological claims to this that the evidence does not support at the strength claimed. As a psychological calibration exercise it is defensible. As a health intervention it is oversold, and for anyone with a history of disordered eating, deliberate hunger is a bad idea full stop.",
  },
];
